import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Nav";
import Footer from "@/components/Footer";

import ReduxProvider from "@/components/providers/ReduxProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <Navbar />
      {children}
      <Footer />
    </ReduxProvider>
  );
}
