-- CreateTable
CREATE TABLE "Article" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "overview" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "howToTake" TEXT NOT NULL,
    "benefits" JSONB NOT NULL,
    "overallRating" DOUBLE PRECISION NOT NULL,
    "ingredientsRating" DOUBLE PRECISION NOT NULL,
    "valueRating" DOUBLE PRECISION NOT NULL,
    "manufacturerRating" DOUBLE PRECISION NOT NULL,
    "safetyRating" DOUBLE PRECISION NOT NULL,
    "brandHighlights" JSONB NOT NULL,
    "keyIngredients" JSONB NOT NULL,
    "pros" JSONB NOT NULL,
    "cons" JSONB NOT NULL,
    "safety" TEXT NOT NULL,
    "effectiveness" TEXT NOT NULL,
    "pricing" JSONB NOT NULL,
    "manufacturerInfo" JSONB NOT NULL,
    "howItWorks" TEXT NOT NULL,
    "ingredients" JSONB NOT NULL,
    "faqs" JSONB NOT NULL,
    "customerReviews" JSONB NOT NULL,
    "conclusion" TEXT NOT NULL,
    "officialWebsite" TEXT NOT NULL,
    "productImage" TEXT NOT NULL,
    "ctaButtons" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
);
